### ISSUE TITLE
Auto start CI for collaborators

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1180]
Hey, is there a easy possibility to automatically run the CI for any PR that was opened by a collaborator and also in case there is a update? That would ease the work for all of us when opening and maintaining PRs.

I guess we might need a bot to do this but right now I have to little insight into the build things to know what might be required / what should be done. Any ideas / suggestions?

**Comment by gibfahn** [comment]
Yes this is possible, in fact we already started working on it, the reason it stalled was because no-one had the time to really push it forward.

The bot that co-ordinates it would be the github-bot.

See also:

https://github.com/nodejs/github-bot/issues/82
https://github.com/nodejs/github-bot/issues/146

**Comment by BridgeAR** [comment]
That is great! Do you know what has to be done to get this going again? I would really love to get this.

**Comment by gibfahn** [comment]
>That is great! Do you know what has to be done to get this going again? I would really love to get this.

What we were doing before was testing that it works with CitGM. However we hit failures where builds weren't triggered (see https://github.com/nodejs/github-bot/issues/146). 

So someone needs to basically fix that in something that isn't nodejs/node (e.g. in citgm), and once we have it stable we can propose it for nodejs/node and have that discussion.

**Comment by mhdawson** [comment]
I'd recommend that it only start after there is at least one additional approval for the PR.

**Comment by bnoordhuis** [comment]
nodejs/github-bot#146 was closed.  Does that mean this is good to go now?  I'd be a-okay with enabling it for libuv and node-gyp as well.

**Comment by maclover7** [comment]
@LucaLanziani The reason to do this via `nodejs/github-bot` is because we already have many GitHub automation tasks that live in that Node app. Also, the Build WG lately has been moving toward keeping as much configuration in-repo as possible

**Comment by LucaLanziani** [comment]
@maclover7 yeah I supposed one reason was the access. My idea was to use something similar to https://jenkins.io/doc/book/pipeline/jenkinsfile/
The jenkinsfile will live in the repo you want to test and jenkins will scan the repos and load the jobs/set the hooks ect ect.

**Comment by maclover7** [comment]
Largely solved by https://github.com/nodejs/github-bot/pull/178, https://github.com/nodejs/github-bot/pull/180

**Comment by refack** [comment]
> <ins>Largely</ins> solved by

So still not completely solved, please keep WIPs open, otherwise we lose track.

**Comment by mmarchini** [comment]
Can we have a list of tasks we need to accomplish before closing this?

**Comment by Trott** [comment]
I think the auto-kickoff of the Lite job for Collaborators solves this. I wouldn't want a full CI kickoff for doc edits and whatnot. I think the current situation is 👍. Feel free to re-open if you think that's misguided. Just doing my best to triage right now.
